version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: api
    restart: always
    volumes:
      - ./:/usr/src/app/
    ports:
      - "${APP_PORT}:${DOCKER_PORT}"
    external_links:
      - db
      - redis
    depends_on:
      - db
      - redis
    networks:
      - express
  db:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./docker/mongodb/config/mongod.conf:/etc/mongod.conf
      - ./docker/mongodb/data/log/:/var/log/mongodb/
      - ./docker/mongodb/data/db/:/data/db
    networks:
      - express
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - express

networks:
  express:
    driver: bridge